### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by notedwin-dev** [iulspop/slack-web-scraper#11]
![image](https://user-images.githubusercontent.com/54582223/202164486-9c946205-047c-4019-81be-0dfc64c95032.png)

![image](https://user-images.githubusercontent.com/54582223/202164771-a7fa2df2-880b-4cdc-b057-3585a61a12e2.png)

- [x] Sender name is now empty and had turned into a clickable button.
- [x] text is now wrapped in div.
- [ ] sometimes emoji reactions menu show up in it and isn't filtered properly.

**Comment by Edwin15857** [comment]
#12 fixed sender name and text wrapped in div issue
