### ISSUE TITLE
Never get past login page

### ISSUE THREAD

**Issue by jamesmurdza** [iulspop/slack-web-scraper#9]
I can't get this scraper to work. Even if the cookies are written already, I get stuck on the login page:

Here's a video of what I see: https://drive.google.com/file/d/1zEEN16_0TB3kOMebiolmvdSaAKbunvE3/view?usp=sharing

If I manually type in my details here, it still fails, saying the channel can't be found, without waiting for the page to finish loading.

**Comment by williamdes** [comment]
Quite strange

**Comment by jamesmurdza** [comment]
I don't have a good hunch as to why it's doing this. Do you think it is a system issue or an issue with the slack workspace itself?

**Comment by iulspop** [comment]
Did you get the cookies from signing in with SSO? I believe OAuth 2.0 based SSO won't work when using an automated browser, even if you save the cookies before-hand from a sign-in on a normal browser. However, I'm not sure and I need to investigate this more.

**Comment by iulspop** [comment]
"If I manually type in my details here, it still fails, saying the channel can't be found, without waiting for the page to finish loading."

Hmm, this sounds instead like a problem with the collect script code. It sounds like it finds your cookies, but then goes to the page, and even though they're applied, the Slack Workspace doesn't load.

I might be able to debug this Sunday. I'll keep you posted.

**Comment by jamesmurdza** [comment]
The page doesn't get the chance to load. It looks like the script is failing before the page has finished loading.

**Comment by jamesmurdza** [comment]
If you could containerize the scraper I could run that, and see if it an issue with dependencies.

**Comment by jamesmurdza** [comment]
Update: I have bypassed the DOM now and am using Slack's (private?) JSON API. Happy to share my solution if it's helpful.

**Comment by iulspop** [comment]
@jamesmurdza if you have access to Slack's JSON API, then that's a far more reliable and convenient solution than the scraper :)

**Comment by jamesmurdza** [comment]
@iulspop There is an endpoint at: https://airtable.com/v0.3/view/AIRTABLEID/readSharedViewData

It works so long as the right GET parameters and session cookies are used.

**Comment by mkantautas** [comment]
@iulspop  The problem with the slack API is that it doesn't provide access to some crucial data - like huddle call duration. Neither you can search for it via the web or native apps. So custom scrapers are the only way.

**Comment by iulspop** [comment]
@mkantautas this scraper doesn't collect that information on huddles. Happy to accept your contributions if you'd like to add that feature! You can open a draft PR and I answer questions.

**Comment by mkantautas** [comment]
@iulspop I beg to differ:

![image](https://user-images.githubusercontent.com/19753711/211173318-dd176fdc-278f-4bb8-8feb-ae659a8754f1.png)

Also fixed the email Oauth problem. With a `page.waitFor(25000);` to fill in the email and verification code myself - a hack, but works for now.

But yeah, have my hands full atm - but hopefully will have a window to do a somewhat clean PR as a feature for the huddle scrape option.

**Comment by iulspop** [comment]
@mkantautas neat! I didn't expect the huddle info to be right there in the posts from the chat.

Ouuh so you go it to work? Was it the SSO method where you click your Google Account and then authorize? When I tested it myself using a similar pause method to do it manually, it didn't work on the automated browser even when installing a plugin to obscure the browser was automated. No matter which way I did it, it only worked on a normal browser.

**Comment by mkantautas** [comment]
@iulspop 

I actually used the email login - when they send you the verification 6 digit code to your email.

Besides the wait, because of the whole manual activity, you need to add another goto so the logic wouldn't break after the `waitFor` ends.

```
async function gotoWorkspace(page) {
  await page.goto(process.env.SLACK_WORKSPACE_URL, {timeout: 0})
  await page.waitFor(25000);
  await page.goto(process.env.SLACK_WORKSPACE_URL, {timeout: 0})
  await page.waitForNavigation({ waitUntil: 'load' })
}

**Comment by ahonnecke** [comment]
I also have experienced this issue, and the jan 8 fix did not resolve it.  This does not seem to be a working automated solution.
